// Static ticker → company name map for S&P 500 companies (historical + current)
const COMPANY_NAMES: Record<string, string> = {
  A: "Agilent Technologies",
  AAL: "American Airlines",
  AAP: "Advance Auto Parts",
  AAPL: "Apple",
  ABT: "Abbott Laboratories",
  ACS: "Affiliated Computer Services",
  ADBE: "Adobe",
  ADI: "Analog Devices",
  ADM: "Archer-Daniels-Midland",
  ADP: "Automatic Data Processing",
  ADSK: "Autodesk",
  AES: "AES Corporation",
  AET: "Aetna",
  AIG: "American International Group",
  AIV: "Apartment Investment & Management",
  AIZ: "Assurant",
  AKAM: "Akamai Technologies",
  ALB: "Albemarle",
  ALGN: "Align Technology",
  ALK: "Alaska Air Group",
  ALL: "Allstate",
  ALLE: "Allegion",
  AMD: "Advanced Micro Devices",
  AME: "Ametek",
  AMGN: "Amgen",
  AMP: "Ameriprise Financial",
  AMT: "American Tower",
  AMTM: "Amentum Holdings",
  AMZN: "Amazon",
  AN: "AutoNation",
  ANDV: "Andeavor",
  ANF: "Abercrombie & Fitch",
  AON: "Aon",
  APA: "APA Corporation",
  APH: "Amphenol",
  ASH: "Ashland",
  ASN: "Archstone-Smith Trust",
  ATGE: "Adtalem Global Education",
  ATI: "ATI Inc.",
  AVB: "AvalonBay Communities",
  AXP: "American Express",
  AYI: "Acuity Brands",
  AZO: "AutoZone",
  BA: "Boeing",
  BAC: "Bank of America",
  BAX: "Baxter International",
  BBY: "Best Buy",
  BDX: "Becton Dickinson",
  BEN: "Franklin Resources",
  BIIB: "Biogen",
  BK: "Bank of New York Mellon",
  BKNG: "Booking Holdings",
  BLK: "BlackRock",
  BLS: "BellSouth",
  BMS: "Bemis Company",
  BOL: "Bausch & Lomb",
  BRL: "Barr Pharmaceuticals",
  BSC: "Bear Stearns",
  BSX: "Boston Scientific",
  BWA: "BorgWarner",
  C: "Citigroup",
  CAR: "Avis Budget Group",
  CARR: "Carrier Global",
  CAT: "Caterpillar",
  CB: "Chubb",
  CBE: "Cooper Industries",
  CBRE: "CBRE Group",
  CCK: "Crown Holdings",
  CCL: "Carnival Corporation",
  CCU: "Clear Channel",
  CF: "CF Industries",
  CFC: "Countrywide Financial",
  CFG: "Citizens Financial Group",
  CI: "Cigna",
  CIEN: "Ciena",
  CIN: "Cincinnati Financial",
  CINF: "Cincinnati Financial",
  CL: "Colgate-Palmolive",
  CLF: "Cleveland-Cliffs",
  CLX: "Clorox",
  CMA: "Comerica",
  CMCSA: "Comcast",
  CME: "CME Group",
  CMG: "Chipotle Mexican Grill",
  CMI: "Cummins",
  CMS: "CMS Energy",
  CMVT: "Comverse Technology",
  CNC: "Centene",
  CNP: "CenterPoint Energy",
  CNX: "CNX Resources",
  COF: "Capital One",
  COL: "Rockwell Collins",
  COO: "CooperCompanies",
  COP: "ConocoPhillips",
  COTY: "Coty",
  COV: "Covidien",
  CPB: "Campbell Soup",
  CPRI: "Capri Holdings",
  CPWR: "Compuware",
  CRM: "Salesforce",
  CSRA: "CSRA Inc.",
  CSX: "CSX Corporation",
  CTAS: "Cintas",
  CTRA: "Coterra Energy",
  CVG: "Convergys",
  CVS: "CVS Health",
  CZR: "Caesars Entertainment",
  DAL: "Delta Air Lines",
  DD: "DuPont",
  DDR: "DDR Corp",
  DDS: "Dillard's",
  DE: "Deere & Company",
  DG: "Dollar General",
  DGX: "Quest Diagnostics",
  DHI: "D.R. Horton",
  DHR: "Danaher",
  DLTR: "Dollar Tree",
  DRI: "Darden Restaurants",
  DTE: "DTE Energy",
  DUK: "Duke Energy",
  DVA: "DaVita",
  DVN: "Devon Energy",
  DXC: "DXC Technology",
  DXCM: "DexCom",
  EA: "Electronic Arts",
  EBAY: "eBay",
  ECL: "Ecolab",
  EFX: "Equifax",
  EG: "Everest Group",
  EHC: "Encompass Health",
  EIX: "Edison International",
  EL: "Estée Lauder",
  EMN: "Eastman Chemical",
  EMR: "Emerson Electric",
  ENPH: "Enphase Energy",
  EOG: "EOG Resources",
  EP: "El Paso Corporation",
  EPAM: "EPAM Systems",
  EQIX: "Equinix",
  EQT: "EQT Corporation",
  ES: "Eversource Energy",
  ESRX: "Express Scripts",
  ETN: "Eaton Corporation",
  ETR: "Entergy",
  ETSY: "Etsy",
  EVHC: "Envision Healthcare",
  EXPD: "Expeditors International",
  EXPE: "Expedia Group",
  F: "Ford Motor",
  FANG: "Diamondback Energy",
  FAST: "Fastenal",
  FBF: "FleetBoston Financial",
  FCX: "Freeport-McMoRan",
  FDX: "FedEx",
  FE: "FirstEnergy",
  FFIV: "F5 Networks",
  FHN: "First Horizon",
  FITB: "Fifth Third Bancorp",
  FL: "Foot Locker",
  FLR: "Fluor",
  FLS: "Flowserve",
  FMC: "FMC Corporation",
  FMCC: "Freddie Mac",
  FNMA: "Fannie Mae",
  FOSL: "Fossil Group",
  FSLR: "First Solar",
  FTI: "TechnipFMC",
  GAS: "NICOR Inc.",
  GDW: "Golden West Financial",
  GE: "General Electric",
  GEHC: "GE HealthCare",
  GHC: "Graham Holdings",
  GILD: "Gilead Sciences",
  GIS: "General Mills",
  GLK: "Graco Inc.",
  GLW: "Corning",
  GM: "General Motors",
  GME: "GameStop",
  GNRC: "Generac",
  GNW: "Genworth Financial",
  GR: "Goodrich Corporation",
  GS: "Goldman Sachs",
  GT: "Goodyear",
  HAL: "Halliburton",
  HAR: "Harman International",
  HAS: "Hasbro",
  HBAN: "Huntington Bancshares",
  HBI: "Hanesbrands",
  HES: "Hess Corporation",
  HIG: "Hartford Financial",
  HOG: "Harley-Davidson",
  HP: "Helmerich & Payne",
  HPE: "Hewlett Packard Enterprise",
  HPQ: "HP Inc.",
  HRB: "H&R Block",
  HST: "Host Hotels & Resorts",
  HUM: "Humana",
  ICE: "Intercontinental Exchange",
  IGT: "International Game Technology",
  ILMN: "Illumina",
  INCY: "Incyte",
  INTC: "Intel",
  INTU: "Intuit",
  IPG: "Interpublic Group",
  IR: "Ingersoll Rand",
  IRM: "Iron Mountain",
  ISRG: "Intuitive Surgical",
  ITT: "ITT Inc.",
  ITW: "Illinois Tool Works",
  IVZ: "Invesco",
  J: "Jacobs Solutions",
  JBL: "Jabil",
  JCI: "Johnson Controls",
  JEF: "Jefferies Financial",
  JNPR: "Juniper Networks",
  JNY: "Jones Apparel Group",
  JPM: "JPMorgan Chase",
  JWN: "Nordstrom",
  K: "Kellanova",
  KBH: "KB Home",
  KDP: "Keurig Dr Pepper",
  KEY: "KeyCorp",
  KG: "King Pharmaceuticals",
  KHC: "Kraft Heinz",
  KIM: "Kimco Realty",
  KLAC: "KLA Corporation",
  KMG: "Kerr-McGee",
  KMX: "CarMax",
  KR: "Kroger",
  KSS: "Kohl's",
  LEG: "Leggett & Platt",
  LEN: "Lennar",
  LHX: "L3Harris Technologies",
  LLY: "Eli Lilly",
  LMT: "Lockheed Martin",
  LNC: "Lincoln National",
  LOW: "Lowe's",
  LPX: "Louisiana-Pacific",
  LRCX: "Lam Research",
  LUV: "Southwest Airlines",
  LVS: "Las Vegas Sands",
  LW: "Lamb Weston",
  LYB: "LyondellBasell",
  M: "Macy's",
  MA: "Mastercard",
  MAC: "Macerich",
  MAR: "Marriott International",
  MAS: "Masco",
  MAT: "Mattel",
  MBI: "MBIA",
  MCD: "McDonald's",
  MCK: "McKesson",
  MCO: "Moody's",
  MEE: "Massey Energy",
  MET: "MetLife",
  META: "Meta Platforms",
  MLM: "Martin Marietta",
  MMC: "Marsh McLennan",
  MMM: "3M",
  MNST: "Monster Beverage",
  MO: "Altria Group",
  MOLX: "Molex",
  MOS: "Mosaic Company",
  MPC: "Marathon Petroleum",
  MPWR: "Monolithic Power",
  MRK: "Merck",
  MRNA: "Moderna",
  MS: "Morgan Stanley",
  MSI: "Motorola Solutions",
  MTB: "M&T Bank",
  MTCH: "Match Group",
  MTG: "MGIC Investment",
  MU: "Micron Technology",
  MUR: "Murphy Oil",
  NAVI: "Navient",
  NBR: "Nabors Industries",
  NCLH: "Norwegian Cruise Line",
  NDAQ: "Nasdaq Inc.",
  NEE: "NextEra Energy",
  NEM: "Newmont",
  NFLX: "Netflix",
  NFX: "Newpark Resources",
  NKTR: "Nektar Therapeutics",
  NOC: "Northrop Grumman",
  NOV: "NOV Inc.",
  NRG: "NRG Energy",
  NSC: "Norfolk Southern",
  NTAP: "NetApp",
  NTRS: "Northern Trust",
  NUE: "Nucor",
  NVDA: "Nvidia",
  NWL: "Newell Brands",
  NWSA: "News Corp",
  NXPI: "NXP Semiconductors",
  NYT: "New York Times",
  ODP: "Office Depot",
  OI: "O-I Glass",
  OKE: "ONEOK",
  OMC: "Omnicom Group",
  OMX: "OfficeMax",
  ORCL: "Oracle",
  ORLY: "O'Reilly Automotive",
  OXY: "Occidental Petroleum",
  PARA: "Paramount Global",
  PBG: "Pepsi Bottling Group",
  PBI: "Pitney Bowes",
  PCAR: "Paccar",
  PCG: "PG&E",
  PEG: "Public Service Enterprise",
  PEP: "PepsiCo",
  PFE: "Pfizer",
  PFG: "Principal Financial",
  PGR: "Progressive",
  PH: "Parker-Hannifin",
  PHM: "PulteGroup",
  PLD: "Prologis",
  PNC: "PNC Financial",
  PNW: "Pinnacle West Capital",
  PPG: "PPG Industries",
  PPL: "PPL Corporation",
  PRD: "Polaroid",
  PRGO: "Perrigo",
  PTC: "PTC Inc.",
  PVH: "PVH Corp",
  PWR: "Quanta Services",
  QCOM: "Qualcomm",
  QRVO: "Qorvo",
  R: "Ryder System",
  RCL: "Royal Caribbean",
  REGN: "Regeneron",
  RF: "Regions Financial",
  RHI: "Robert Half",
  RIG: "Transocean",
  RL: "Ralph Lauren",
  ROH: "Rohm and Haas",
  ROK: "Rockwell Automation",
  ROST: "Ross Stores",
  RRC: "Range Resources",
  SANM: "Sanmina",
  SBAC: "SBA Communications",
  SBUX: "Starbucks",
  SCG: "SCANA Corporation",
  SCHW: "Charles Schwab",
  SEE: "Sealed Air",
  SFA: "Scientific-Atlanta",
  SGP: "Schering-Plough",
  SHW: "Sherwin-Williams",
  SIG: "Signet Jewelers",
  SLB: "Schlumberger",
  SLG: "SL Green Realty",
  SLM: "SLM Corporation",
  SLR: "Solectron",
  SMCI: "Super Micro Computer",
  SNA: "Snap-on",
  SO: "Southern Company",
  SPGI: "S&P Global",
  SRCL: "Stericycle",
  STX: "Seagate Technology",
  STZ: "Constellation Brands",
  SVU: "Supervalu",
  SWK: "Stanley Black & Decker",
  SWKS: "Skyworks Solutions",
  SYY: "Sysco",
  TDC: "Teradata",
  TDG: "TransDigm",
  TEL: "TE Connectivity",
  TER: "Teradyne",
  TGNA: "Tegna",
  TGT: "Target",
  THC: "Tenet Healthcare",
  TIE: "Titanium Metals",
  TIN: "Temple-Inland",
  TJX: "TJX Companies",
  TLAB: "Tellabs",
  TMUS: "T-Mobile US",
  TPR: "Tapestry",
  TRB: "Tribune Company",
  TRIP: "Tripadvisor",
  TROW: "T. Rowe Price",
  TSCO: "Tractor Supply",
  TSLA: "Tesla",
  TSN: "Tyson Foods",
  TT: "Trane Technologies",
  TTWO: "Take-Two Interactive",
  TWX: "Time Warner",
  TXN: "Texas Instruments",
  TXT: "Textron",
  TYL: "Tyler Technologies",
  UA: "Under Armour",
  UAA: "Under Armour",
  UAL: "United Airlines",
  UHS: "Universal Health Services",
  UIS: "Unisys",
  ULTA: "Ulta Beauty",
  UNM: "Unum Group",
  UNP: "Union Pacific",
  URBN: "Urban Outfitters",
  URI: "United Rentals",
  USB: "U.S. Bancorp",
  UVN: "Univision",
  V: "Visa",
  VFC: "VF Corporation",
  VIAV: "Viavi Solutions",
  VLO: "Valero Energy",
  VMC: "Vulcan Materials",
  VRSN: "VeriSign",
  VRTX: "Vertex Pharmaceuticals",
  VST: "Vistra",
  WBA: "Walgreens Boots Alliance",
  WBD: "Warner Bros. Discovery",
  WDC: "Western Digital",
  WEN: "Wendy's",
  WFC: "Wells Fargo",
  WHR: "Whirlpool",
  WM: "Waste Management",
  WMB: "Williams Companies",
  WOR: "Worthington Industries",
  WU: "Western Union",
  WY: "Weyerhaeuser",
  WYNN: "Wynn Resorts",
  X: "United States Steel",
  XEL: "Xcel Energy",
  XRAY: "Dentsply Sirona",
  XRX: "Xerox",
  YUM: "Yum! Brands",
  ZBH: "Zimmer Biomet",
  ZION: "Zions Bancorporation",
  ZTS: "Zoetis",
};

export function getCompanyName(ticker: string): string {
  return COMPANY_NAMES[ticker] || ticker;
}

export function getCompanyInitial(ticker: string): string {
  const name = COMPANY_NAMES[ticker];
  if (!name) return ticker.charAt(0);
  return name.charAt(0);
}
